name: votre_projet
description: "Un projet Flutter de base."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  permission_handler: ^11.3.1
  device_preview: ^1.1.1
  sqflite: ^2.3.0
  path: ^1.9.0
  sqflite_common_ffi: ^2.3.4+4
  http: ^1.2.2
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  mobile_scanner: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
